# Version which is often tracked by Sprint number
version: '2.057'

# Any Alexis application can use this authentication list definition
authentication_list:
  # Required keys: name, type, description, headers

  - name: 'opsgenie_test_fireinthehole'
    type: 'opsgenie'
    description: 'Alexis 2.0 - test_fireinthehole'
    headers: '{"Authorization":"GenieKey 930djvn3-3ndj-19dj-dj3f-39djivk210dk"}'

# Classifier
classifier:

  # Define specific action handlers
  action_handler_destinations:
    linux: 'http://action_handler/v1'

  # Define the default queue to place alerts if they
  # successfully pass all evaluations for a particular rule
  default_remediation_queue: 'queue_autoremediation'
  # Define the default queue to place alerts if they
  # pass NO rules
  default_investigation_queue: 'queue_needsinvestigation'
  development: 'true'

  # The listener is only respected if running python via cli
  listener:
    hostname: '0.0.0.0'
    port: '8083'
    protocol: 'http' # Not currently in use

  # Define tokens for the application
  tokens:
    # This is the list of tokens permitted to communicate with the application
    allowed_clients: 'clients.classifier.json'
    # This is the directory where the tokens are located
    directory: 'tokens'
    # This is the token used by the application to connect to other
    # Alexis applications and instances
    runtime: 'localhost.token.json'
